name: wiki-full-sync

on:
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          set -e
          git config --global user.name "wiki-bot"
          git config --global user.email "bot@example.com"

      - name: clone source wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -e
          SRC_URL="https://${GH_TOKEN}@github.com/solaris0115/rimworld-dev-korea.wiki.git"
          git clone "${SRC_URL}" source.wiki

      - name: clone target wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -e
          TGT_URL="https://${GH_TOKEN}@github.com/solaris0115/rimworld-dev-korea.wiki.git"
          git clone "${TGT_URL}" target.wiki

      - name: build rsync rules
        run: |
          set -e
          printf "%s\n" "+ */" "+ *.md" "+ _Sidebar.md" "+ _Footer.md" "+ _*.*" "+ _images/***" "- *" > rsync.rules
          cat rsync.rules

      - name: sanitize filenames in source (colon to dash)
        run: |
          set -e
          find source.wiki -depth -name '*:*' | while read -r f; do
