name: wiki-full-sync

on:
  push:
    branches: [ main, master ]   # 메인 리포에 커밋 발생 시 자동 실행
  schedule:
    - cron: "*/30 * * * *"       # 30분마다 실행(UTC 기준)
  workflow_dispatch: {}           # 필요시 수동 실행도 가능

concurrency:
  group: wiki-full-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config --global user.name "wiki-bot"
          git config --global user.email "bot@example.com"

      - name: clone source wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Fine-grained PAT(Contents: Read/Write)
        run: |
          SRC_URL="https://${GH_TOKEN}@github.com/solaris0115/rimworld-dev-korea.wiki.git"
          echo "Cloning source: $SRC_URL"
          git clone "$SRC_URL" source.wiki

      - name: clone target wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TGT_URL="https://${GH_TOKEN}@github.com/solaris0115/rimworld-dev-korea.wiki.git"
          echo "Cloning target: $TGT_URL"
          git clone "$TGT_URL" target.wiki

      - name: build rsync rules
        run: |
          printf "%s\n" \
            "+ */" \
            "+ *" \
            "- *" > rsync.rules
            
          cat rsync.rules

      - name: sanitize filenames in source (colon -> dash)
        run: |
          # ':' 포함 파일/폴더명을 '-'로 치환
          find source.wiki -depth -name '*:*' | while read -r f; do
            safe="$(echo "$f" | sed 's/:/-/g')"
            if [ "$f" != "$safe" ]; then
              echo "Renaming: $f -> $safe"
              mkdir -p "$(dirname "$safe")"
              mv "$f" "$safe"
            fi
          done

      - name: rsync full sync (with delete)
        run: |
          rsync -av --delete --prune-empty-dirs --filter="merge rsync.rules" \
            source.wiki/ target.wiki/

      - name: commit if changes
        id: commit
        run: |
          cd target.wiki
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore(wiki): full sync from solaris0115/rimworld-dev-korea.wiki"
            echo "committed=yes" >> "$GITHUB_OUTPUT"
          else
            echo "committed=no" >> "$GITHUB_OUTPUT"
          fi

      - name: push
        if: steps.commit.outputs.committed == 'yes'
        run: |
          cd target.wiki
          git push origin master   # 위키 기본 브랜치
