      - name: pre-pull with stash (avoid non-ff race)
        id: prepull
        run: |
          cd target.wiki
          # 변경이 있으면 임시 보관
          if [ -n "$(git status --porcelain)" ]; then
            git stash push -u -m "sync-stash" || true
            STASHED=yes
          else
            STASHED=no
          fi
          echo "stashed=$STASHED" >> "$GITHUB_OUTPUT"

          # 원격 최신 반영
          git fetch origin master || true
          git rebase origin/master || git reset --hard origin/master

          # 스태시 복원(있을 때만)
          if [ "$STASHED" = "yes" ]; then
            git stash pop || true
          fi

          # 복원 후 변경 있으면 커밋
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "docs(wiki): sync from main repo ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
            echo "committed=yes" >> "$GITHUB_OUTPUT"
          else
            echo "committed=no" >> "$GITHUB_OUTPUT"
          fi
